/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 22:05:52 GMT 2024
 */

package hr.algebra.utils.CustomExceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import hr.algebra.utils.CustomExceptions.CustomAlreadyExistsException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CustomAlreadyExistsException_ESTest extends CustomAlreadyExistsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomAlreadyExistsException customAlreadyExistsException0 = new CustomAlreadyExistsException("");
  }
}
